#!/bin/bash
# 
# Backup script
# 

# Format: YEAR MONTH DAY
DATE=$(date +%Y%m%d)

INCLUDE1="/home/shaggy/.vimrc /home/shaggy/.abook /home/shaggy/.calcurse /home/shaggy/.colors"
INCLUDE2="/home/shaggy/.config/bspwm /home/shaggy/.config/dwb /home/shaggy/.config/htop /home/shaggy/.config/mpd"
INCLUDE3="/home/shaggy/.config/mps-youtube /home/shaggy/.config/mpv /home/shaggy/.config/Mumble /home/shaggy/.config/qutebrowser"
INCLUDE4="/home/shaggy/.config/ranger /home/shaggy/.config/sxhkd /home/shaggy/.config/sxiv /home/shaggy/.config/wmfs"
INCLUDE5="/home/shaggy/.config/youtube-viewer /home/shaggy/.cortex /home/shaggy/.fluxbox"
INCLUDE6="/home/shaggy/.irssi /home/shaggy/.i3 /home/shaggy/.mpv /home/shaggy/.mutt /home/shaggy/.muttrc"
INCLUDE7="/home/shaggy/.nano /home/shaggy/.ncmpcpp /home/shaggy/.newsbeuter /home/shaggy/.offlineimap"
INCLUDE8="/home/shaggy/.ssh /home/shaggy/.turses /home/shaggy/.password-store"
INCLUDE9="/home/shaggy/.weechat /home/shaggy/scripts /home/shaggy/.aliasrc"
INCLUDE10="/home/shaggy/.cliweather /home/shaggy/.conkyrc /home/shaggy/.gitconfig /home/shaggy/.goobook_cache"
INCLUDE11="/home/shaggy/.msmtprc /home/shaggy/.nanorc /home/shaggy/.netrc /home/shaggy/.offlineimaprc"
INCLUDE12="/home/shaggy/.notmuch-config /home/shaggy/.Xdefaults /home/shaggy/.xinitrc /home/shaggy/.xprofile"
INCLUDE13="/home/shaggy/.zshrc /home/shaggy/.zsh_history /home/shaggy/.screenrc"
INCLUDE14="/home/shaggy/scripts /home/shaggy/private /home/shaggy/.gnupg"

BACKUPDIRARCH=/riddlebox/Dropbox/backups/archconfigs/
 




# Target file
TARTARGET="/riddlebox/Dropbox/backups/backup.tar.gz"
ETCTARTARGET="/riddlebox/Dropbox/backups/ETC.tar.gz"

TARTARGETMAIL="/riddlebox/Dropbox/backups/backupmail-$DATE.tar.gz"

#tar -czvf $TARTARGET $MYSQLTARGET /home/code/bots /var/config /var/system

tar -czvf $TARTARGETMAIL /home/shaggy/Maildir

tar -czvf $TARTARGET /home/shaggy/bin $INCLUDE1 $INCLUDE2 $INCLUDE3 $INCLUDE4 $INCLUDE5 $INCLUDE6 $INCLUDE7 $INCLUDE8 $INCLUDE9 $INCLUDE10 $INCLUDE11 $INCLUDE12 $INCLUDE13 $INCLUDE14 


tar -czvf $ETCTARTARGET /etc

#nice -n 19 rsync --archive --force --delete --progress --compress /etc $BACKUPDIRARCH


