#!/bin/sh

#mkdir convert

for f in *.avi; do ffmpeg -i "$f" "${f%.avi}.mkv"; done


#find -name '*.avi' -exec ffmpeg -i {} {}.mp4 \;


#find a safe way to delete old files?
#find . -name "*.avi.mp4" -exec rename 's/\.avi.mp4$/\.mp4/i' {} \;
