#!/bin/bash

STATUS=$(dropbox-cli status)

if [ "$STATUS" == "Dropbox isn't running!" ]; then
    START=$(dropbox-cli start)
fi

COUNT_DONE=1
while true
do
    STATUS=$(dropbox-cli status)
    if [ "$STATUS" == "Up to date" ]; then
            COUNT_DONE=`expr $COUNT_DONE + 1`
            if [ $COUNT_DONE -gt 10 ]
            then
                    STOP=$(dropbox-cli stop)
                    break;
            fi
    fi
done
exit 0
