#!/usr/bin/env bash
# AUTHOR:   shaggy
# FILE:     mailupdate
# ROLE:     TODO (some explanation)
# CREATED:  2014-12-21 18:12:50
# MODIFIED: 2014-12-21 19:22:09
offlineimap
cd /home/shaggy/Maildir
git add . 
git commit -am 'mailupdate'

